spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true